### ISSUE TITLE
Chapters missing

### ISSUE THREAD

**Issue by M-AliFida** [PacktPublishing/Red-Hat-Enterprise-Linux-RHEL-9-Administration#2]
I can only see certain chapters - 

chapter-08-remote-systems-administration | Use system roles | 2 years ago
chapter-10-selinux | Add apache script | 2 years ago
chapter-18-exercise1 | Adding files for exercise chapters | 2 years ago
chapter-19-exercise2 | Fix UID/GID | 2 years ago

Where are the other chapters?

Thanks.

**Comment by iranzo** [comment]
Only the chapters with long examples have the equivalent in the repo and, in that case, there's a mention to them in the book

**Comment by M-AliFida** [comment]
Alright thanks, hadn’t got that far yet.
